# Generated by Django 4.1.5 on 2023-01-23 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english_cours', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_exam', to='english_cours.courses')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('con_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_answer', to='english_cours.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=500, primary_key=True, serialize=False)),
                ('con_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_questions', to='english_exam.exams')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOptions',
            fields=[
                ('options', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, primary_key=True, serialize=False)),
                ('con_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_options', to='english_exam.questions')),
            ],
        ),
    ]
